# Generated by Django 6.0.2 on 2026-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('problem_description', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
