# Generated by Django 6.0.2 on 2026-02-17 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['phone'], name='workshop_bo_phone_49a74c_idx'), models.Index(fields=['status'], name='workshop_bo_status_795589_idx')],
            },
        ),
    ]
