# Generated by Django 6.0.2 on 2026-02-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_booking_expected_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
